[profile.default]
src = "src"
out = "out"
libs = ["lib"]
script = "script"
test = "test"

# Specify the default script to use (this should prevent looking for Counter.s.sol)
fs_permissions = [{ access = "read", path = "./"}]

# Optional: Add any other configurations you might need
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
